Create timeseries example for time index
TREEcg/specification pull request #10
Opened 2020-03-16 13:06 UTC by brechtvdv

2020-03-16 13:27 UTC, pietercolpaert commented on examples/timeseries.ttl
> +@prefix sosa: "http://www.w3.org/ns/sosa/".
`<>` not `""`

2020-03-16 13:28 UTC, pietercolpaert commented on examples/timeseries.ttl
> +                                          tree:view </14/8393/5467?2019-07-23T00:00:00.000Z.ttl> . #From the latest sensor page, all elements of one tile can be found through "previous"
`;` not `.` at the end: parse error

2020-03-16 18:47 UTC, brechtvdv commented
Turtle validator gives error with hydra:required true?

2020-03-16 19:14 UTC, pietercolpaert commented
You cannot end with a period in a blank node

2020-03-17 09:06 UTC, pietercolpaert commented
Indenting and coordinates

2020-03-17 10:06 UTC, brechtvdv commented
add tree:timeQuery

2020-03-17 12:31 UTC, brechtvdv commented
@pietercolpaert Should we add a tree:view relation for every tile that contains data? Looks like a good discovery way for harvesting all the data without having to guess through the template

2020-03-17 12:34 UTC, pietercolpaert commented
Yes, otherwise you cannot know that this page is part of the collection. There are 3 options. See discovery spec. I think tree:view here makes sense, as long as you can discover all elements in the collection from that node.

2020-10-24 11:07 UTC, pietercolpaert requested changes
Sorry for the late reaction! Couple of points of feedback still!

2020-10-24 11:07 UTC, pietercolpaert commented on examples/timeseries/14/8393/5467/2020-12-25T150000.ttl
> +                                          tree:relation [     a tree:LowerThanRelation ;
LessThanRelation

2020-10-24 11:07 UTC, pietercolpaert commented on examples/timeseries/14/8393/5467/2020-12-25T150000.ttl
> +
No search form on this page?

2020-10-24 11:07 UTC, pietercolpaert commented on examples/timeseries/airQualityObservations.ttl
> +<https://mycity.example.org/airQualityObservations> a hydra:Collection ;
Let’s change this to a tree:Collection

2020-10-24 11:07 UTC, pietercolpaert commented on examples/timeseries/airQualityObservations.ttl
> +        sh:minInclusive "8393" ;
This is really interesting! Didn’t think of this yet and it is not yet in the spec, but we could include this indeed!

2020-10-24 11:07 UTC, pietercolpaert commented on examples/timeseries/airQualityObservations.ttl
> +        sh:minInclusive "8393" ;
Can you make an issue to add this to the spec?

2020-10-27 09:42 UTC, pietercolpaert commented on examples/timeseries/airQualityObservations.ttl
> +                                                  hydra:search _:b0 .
We’ll change this to `tree:search`!

2020-12-14 13:26 UTC, pietercolpaert approved these changes

2020-12-14 13:26 UTC, pietercolpaert commented on examples/timeseries/airQualityObservations.ttl
> +                                                  hydra:search _:b0 .
And we’ll perform this predicate on the tree:Node instead

2020-12-14 13:26 UTC, merged

2020-12-14 13:26 UTC, pietercolpaert commented
Yes, thanks for this!